### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by TarasMazepa** [modularml/stack-pr#5]
It's nice to see another tool for stacking PRs!

So that you know, I started working on [another tool for stacking](https://github.com/TarasMazepa/stax) in August 2023.

The [readme file of stax](https://github.com/TarasMazepa/stax/blob/main/README.md#alternatives) contains a list of tools that allow stack PRs.

Let me know if anyone of you want to get in touch!

**Comment by ZolotukhinM** [comment]
👋
Nice! Yes, there are a number of alternatives and many of them are great! We called out `ghstack` in our blog post, but we investigated a few others before implementing our own too - most of them were quite viable for us too, but since the tool is relatively simple we went with building our own. Originally it was intended to be a simple internal temporary tool, but then with time we realized that it was quite useful and more-or-less feature complete, so we though that people outside modular might find it useful too :)

Please feel free to try it out if you're interested! We accept contributions and welcome bug reports too! :)

**Comment by TarasMazepa** [comment]
Great decision-making - your own tool is always better especially if it is not very complicated!
